spring:
    application:
        name: shop-ui
    thymeleaf:
        mode: HTML5
        cache: false

server:
    port: 8766

eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
